---
- name: rootfs disk durumuna bak
  shell: "df -h /"
  args:
    executable: "/bin/bash"
  register: disk
 
- name: output rootfs disk durumu
  debug:
    msg: "{{ disk.stdout_lines }}"

- name: install rsyslog
  yum:
   name: rsyslog
   state: present
 
- name: rsyslog restart
  service: "name=rsyslog state=restarted"

